image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}

services:
  - docker:dind


stages:
  - build-base
  - build-base-lang
  - build-cpp-compiler


before_script:
  - docker info
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


# -----------------------------------------
# --- Base Images
# -----------------------------------------
build-base:
  stage: build-base
  script:
    - docker build -t ${DEPLOY_REGISTRY}/base base
    - docker push ${DEPLOY_REGISTRY}/base


# -----------------------------------------
# --- Language Base Images
# -----------------------------------------
build-base-cpp:
  stage: build-base-lang
  script:
    - docker build -t ${DEPLOY_REGISTRY}/base-cpp cpp/base
    - docker push ${DEPLOY_REGISTRY}/base-cpp


# -----------------------------------------
# --- C++ and C Images
# -----------------------------------------
build-gcc-7:
  stage: build-cpp-compiler
  script:
    - docker build -t ${DEPLOY_REGISTRY}/gcc-7 cpp/gcc-7
    - docker push ${DEPLOY_REGISTRY}/gcc-7

build-gcc-6:
  stage: build-cpp-compiler
  script:
    - docker build -t ${DEPLOY_REGISTRY}/gcc-6 cpp/gcc-6
    - docker push ${DEPLOY_REGISTRY}/gcc-6

build-clang-5:
  stage: build-cpp-compiler
  script:
    - docker build -t ${DEPLOY_REGISTRY}/clang-5 cpp/clang-5
    - docker push ${DEPLOY_REGISTRY}/clang-5


