image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}

services:
  - docker:dind


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


build_gcc:
  parallel:
    matrix:
      - VERSION: [13, 12, 11, 10]
  script:
    - docker build -t gcc:${VERSION} --build-arg VERSION=${VERSION} -f gcc/Dockerfile .
    - build/publish_image.sh gcc:${VERSION}

build_clang:
  parallel:
    matrix:
      - VERSION: [16, 14, 15, 13, 12, 11, 10]
  script:
    - docker build -t clang:${VERSION} --build-arg VERSION=${VERSION} -f clang/Dockerfile .
    - build/publish_image.sh clang:${VERSION}

build_arm_none_eabi_gcc:
  parallel:
    matrix:
      - VERSION: [12]
  script:
    - docker build -t arm-none-eabi-gcc:${VERSION} --build-arg VERSION=${VERSION}.3.rel1 -f arm-none-eabi-gcc/Dockerfile .
    - build/publish_image.sh arm-none-eabi-gcc:${VERSION}
