image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}

services:
  - docker:dind


stages:
  - build-docker
  - build-base
  - build-lang-base
  - build-lang-specific
  - release


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}



# -----------------------------------------
# --- Docker Images
# -----------------------------------------
build-docker-build:
  stage: build-docker
  script:
    - script/build-image.sh docker-build docker/docker-build


# -----------------------------------------
# --- Base Images
# -----------------------------------------
build-base:
  stage: build-base
  script:
    - script/build-image.sh base base


# -----------------------------------------
# --- Language Base Images
# -----------------------------------------
build-base-cpp:
  stage: build-lang-base
  script:
    - script/build-image.sh base-cpp cpp/base


# -----------------------------------------
# --- C++ and C Images
# -----------------------------------------
build_c_cpp:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [10, 9, 8, 7, 6]
      - COMPILER: clang
        VERSION: [10, 9, 8, 7, 6, 5]
      - COMPILER: arm-none-eabi-gcc
        VERSION: [9]
  stage: build-lang-specific
  script:
    - script/build-image.sh ${COMPILER}-${VERSION} cpp/${COMPILER} ${VERSION}


# -----------------------------------------
# --- Java
# -----------------------------------------
build_java:
  parallel:
    matrix:
      - JDK: openjdk
        VERSION: [14, 13, 12, 11, 8]
  stage: build-lang-specific
  script:
    - script/build-image.sh ${JDK}-${VERSION}-maven java/maven ${VERSION}


# -----------------------------------------
# --- Release
# -----------------------------------------
release_stable:
  parallel:
    matrix:
      - CATEGORY: base
        IMAGE: [docker-build, base]
      - CATEGORY: c_cpp
        IMAGE: [base-cpp, gcc-10, gcc-9, gcc-8, gcc-7, gcc-6, clang-10, clang-9, clang-8, clang-7, clang-6, clang-5, arm-none-eabi-gcc]
      - CATEGORY: java
        IMAGE: [openjdk-14-maven, openjdk-13-maven, openjdk-12-maven, openjdk-11-maven, openjdk-8-maven]
  stage: release
  script:
    - script/release-image.sh ${IMAGE}
  only:
    - master
