image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}

services:
  - docker:dind


stages:
  - build-base
  - build-lang-base
  - build-lang-specific
  - release


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}



# -----------------------------------------
# --- Base Images
# -----------------------------------------
build-base:
  stage: build-base
  script:
    - script/build-image.sh base base


# -----------------------------------------
# --- Language Base Images
# -----------------------------------------
build-base-cpp:
  stage: build-lang-base
  script:
    - script/build-image.sh base-cpp cpp/base


# -----------------------------------------
# --- C++ and C Images
# -----------------------------------------
build_c_cpp:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [11, 10, 9]
      - COMPILER: clang
        VERSION: [14, 13, 12, 11, 10, 9]
      - COMPILER: arm-none-eabi-gcc
        VERSION: [10]
  stage: build-lang-specific
  script:
    - script/build-image.sh ${COMPILER}-${VERSION} cpp/${COMPILER} ${VERSION}



# -----------------------------------------
# --- Release
# -----------------------------------------
release_stable:
  parallel:
    matrix:
      - CATEGORY: base
        IMAGE: [base]
      - CATEGORY: c_cpp
        IMAGE:
          - base-cpp
          - gcc-11
          - gcc-10
          - gcc-9
          - clang-14
          - clang-13
          - clang-12
          - clang-11
          - clang-10
          - clang-9
          - arm-none-eabi-gcc-10
  stage: release
  script:
    - script/release-image.sh ${IMAGE}
  only:
    - master
