image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}

services:
  - docker:dind


stages:
  - build-base
  - build-base-lang
  - build-cpp-compiler
  - release


before_script:
  - docker info
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


# -----------------------------------------
# --- Base Images
# -----------------------------------------
build-base:
  stage: build-base
  script:
    - script/build-image.sh base base


# -----------------------------------------
# --- Language Base Images
# -----------------------------------------
build-base-cpp:
  stage: build-base-lang
  script:
    - script/build-image.sh base-cpp cpp/base


# -----------------------------------------
# --- C++ and C Images
# -----------------------------------------
build-gcc-7:
  stage: build-cpp-compiler
  script:
    - script/build-image.sh gcc-7 cpp/gcc-7

build-gcc-6:
  stage: build-cpp-compiler
  script:
    - script/build-image.sh gcc-6 cpp/gcc-6

build-clang-5:
  stage: build-cpp-compiler
  script:
    - script/build-image.sh clang-5 cpp/clang-5

build-clang-4:
  stage: build-cpp-compiler
  script:
    - script/build-image.sh clang-4 cpp/clang-4


# -----------------------------------------
# --- Release
# -----------------------------------------
release-stable:
  stage: release
  script:
    - script/release-image.sh base
    - script/release-image.sh base-cpp
    - script/release-image.sh gcc-7
    - script/release-image.sh gcc-6
    - script/release-image.sh clang-5
    - script/release-image.sh clang-4
  only:
    - master

