image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}

services:
  - docker:dind


stages:
  - build-docker
  - build-base
  - build-base-lang
  - build-cpp-compiler
  - build-java-maven
  - release


before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


.build_template: &build_job_base
  retry: 1


# -----------------------------------------
# --- Docker Images
# -----------------------------------------
build-docker-build:
  <<: *build_job_base
  stage: build-docker
  script:
    - script/build-image.sh docker-build docker/docker-build


# -----------------------------------------
# --- Base Images
# -----------------------------------------
build-base:
  <<: *build_job_base
  stage: build-base
  script:
    - script/build-image.sh base base


# -----------------------------------------
# --- Language Base Images
# -----------------------------------------
build-base-cpp:
  <<: *build_job_base
  stage: build-base-lang
  script:
    - script/build-image.sh base-cpp cpp/base


# -----------------------------------------
# --- C++ and C Images
# -----------------------------------------
build-gcc-7:
  <<: *build_job_base
  stage: build-cpp-compiler
  script:
    - script/build-image.sh gcc-7 cpp/gcc 7

build-gcc-6:
  <<: *build_job_base
  stage: build-cpp-compiler
  script:
    - script/build-image.sh gcc-6 cpp/gcc 6

build-clang-5:
  <<: *build_job_base
  stage: build-cpp-compiler
  script:
    - script/build-image.sh clang-5 cpp/clang 5

build-clang-4:
  <<: *build_job_base
  stage: build-cpp-compiler
  script:
    - script/build-image.sh clang-4 cpp/clang 4

build-arm-none-eabi-gcc:
  <<: *build_job_base
  stage: build-cpp-compiler
  script:
    - script/build-image.sh arm-none-eabi-gcc cpp/arm-none-eabi-gcc 7


# -----------------------------------------
# --- Java
# -----------------------------------------
build-openjdk-9-maven:
  <<: *build_job_base
  stage: build-java-maven
  script:
    - script/build-image.sh openjdk-9-maven java/maven 9

build-openjdk-8-maven:
  <<: *build_job_base
  stage: build-java-maven
  script:
    - script/build-image.sh openjdk-8-maven java/maven 8

build-openjdk-7-maven:
  <<: *build_job_base
  stage: build-java-maven
  script:
    - script/build-image.sh openjdk-7-maven java/maven 7


# -----------------------------------------
# --- Release
# -----------------------------------------
release-stable:
  stage: release
  script:
    - script/release-image.sh docker-build
    - script/release-image.sh base
    - script/release-image.sh base-cpp
    - script/release-image.sh gcc-7
    - script/release-image.sh gcc-6
    - script/release-image.sh clang-5
    - script/release-image.sh clang-4
    - script/release-image.sh arm-none-eabi-gcc
  only:
    - master

