image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind


stages:
  - build-base
  - build-base-lang
  - build-cpp-compiler


before_script:
  - docker info
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


# -----------------------------------------
# --- Base Images
# -----------------------------------------
build-base:
  stage: build-base
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/base base
    - docker push ${CI_REGISTRY_IMAGE}/base


# -----------------------------------------
# --- Language Base Images
# -----------------------------------------
build-base-cpp:
  stage: build-base-lang
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/base-cpp cpp/base
    - docker push ${CI_REGISTRY_IMAGE}/base-cpp


# -----------------------------------------
# --- C++ and C Images
# -----------------------------------------
build-gcc-7:
  stage: build-cpp-compiler
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/gcc-7 cpp/gcc-7
    - docker push ${CI_REGISTRY_IMAGE}/gcc-7

