language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DEPLOY_REGISTRY: "registry.gitlab.com/offa/docker-images"


script:
  - script/build-image.sh base base --no-push
  - script/build-image.sh base-cpp cpp/base --no-push
  - script/build-image.sh gcc-7 cpp/gcc-7 --no-push
  - script/build-image.sh gcc-6 cpp/gcc-6 --no-push
  - script/build-image.sh clang-5 cpp/clang-5 --no-push
  - script/build-image.sh clang-4 cpp/clang-4 --no-push

