language: minimal

dist: focal

services:
  - docker

env:
  ## ==== Base
  - IMAGE_NAME: "docker-build"
    DOCKERFILE: "docker/docker-build"

  - IMAGE_NAME: "base"
    DOCKERFILE: "base"

  ## ==== C / C++
  - IMAGE_NAME: "base-cpp"
    DOCKERFILE: "cpp/base"

  - IMAGE_NAME: "gcc-10"
    DOCKERFILE: "cpp/gcc"
    IMG_VERSION: 10

  - IMAGE_NAME: "gcc-9"
    DOCKERFILE: "cpp/gcc"
    IMG_VERSION: 9

  - IMAGE_NAME: "gcc-8"
    DOCKERFILE: "cpp/gcc"
    IMG_VERSION: 8

  - IMAGE_NAME: "gcc-7"
    DOCKERFILE: "cpp/gcc"
    IMG_VERSION: 7

  - IMAGE_NAME: "gcc-6"
    DOCKERFILE: "cpp/gcc"
    IMG_VERSION: 6

  - IMAGE_NAME: "clang-10"
    DOCKERFILE: "cpp/clang"
    IMG_VERSION: 10

  - IMAGE_NAME: "clang-9"
    DOCKERFILE: "cpp/clang"
    IMG_VERSION: 9

  - IMAGE_NAME: "clang-8"
    DOCKERFILE: "cpp/clang"
    IMG_VERSION: 8

  - IMAGE_NAME: "clang-7"
    DOCKERFILE: "cpp/clang"
    IMG_VERSION: 7

  - IMAGE_NAME: "clang-6"
    DOCKERFILE: "cpp/clang"
    IMG_VERSION: 6.0

  - IMAGE_NAME: "clang-5"
    DOCKERFILE: "cpp/clang"
    IMG_VERSION: 5.0

  - IMAGE_NAME: "arm-none-eabi-gcc"
    DOCKERFILE: "cpp/arm-none-eabi-gcc"
    IMG_VERSION: 9


script:
  - export DEPLOY_REGISTRY="registry.gitlab.com/offa/docker-images"
  - export IMAGE_NO_PUSH=true
  - script/build-image.sh ${IMAGE_NAME} ${DOCKERFILE} ${IMG_VERSION}
