language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DEPLOY_REGISTRY: "registry.gitlab.com/offa/docker-images"
    - IMAGE_NO_PUSH: true


script:
  - script/build-image.sh base base
  - script/build-image.sh base-cpp cpp/base
  - script/build-image.sh gcc-7 cpp/gcc 7
  - script/build-image.sh gcc-6 cpp/gcc 6
  - script/build-image.sh clang-5 cpp/clang 5
  - script/build-image.sh clang-4 cpp/clang 4
  - script/build-image.sh arm-none-eabi-gcc cpp/arm-none-eabi-gcc 6

