language: minimal

dist: focal

services:
  - docker

env:
  global:
    - DEPLOY_REGISTRY: "registry.gitlab.com/offa/docker-images"
    - IMAGE_NO_PUSH: true


script:
  # Base
  - script/build-image.sh docker-build docker/docker-build
  - script/build-image.sh base base
  # C++
  - script/build-image.sh base-cpp cpp/base
  - script/build-image.sh gcc-10 cpp/gcc 10
  - script/build-image.sh gcc-9 cpp/gcc 9
  - script/build-image.sh gcc-8 cpp/gcc 8
  - script/build-image.sh gcc-7 cpp/gcc 7
  - script/build-image.sh gcc-6 cpp/gcc 6
  - script/build-image.sh clang-10 cpp/clang 10
  - script/build-image.sh clang-9 cpp/clang 9
  - script/build-image.sh clang-8 cpp/clang 8
  - script/build-image.sh clang-7 cpp/clang 7
  - script/build-image.sh clang-6 cpp/clang 6.0
  - script/build-image.sh clang-5 cpp/clang 5.0
  - script/build-image.sh arm-none-eabi-gcc cpp/arm-none-eabi-gcc 8
  # Java
  - script/build-image.sh openjdk-8-maven java/maven 8
  - script/build-image.sh openjdk-11-maven java/maven 11
  - script/build-image.sh openjdk-12-maven java/maven 12
  - script/build-image.sh openjdk-13-maven java/maven 13
  - script/build-image.sh openjdk-13-maven java/maven 14
