FROM ubuntu:16.04

RUN  apt-get update && apt-get -y upgrade && \
        apt-get install -y --no-install-recommends cmake git software-properties-common && \
        apt-get autoclean && apt-get autoremove

